name: Optimize images to WebP

on:
  push:
    branches: [main]
    paths:
      - 'public/images/**'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install webp tools
        run: |
          sudo apt-get update
          sudo apt-get install -y webp

      - name: Convert PNG/JPG to WebP (q=80)
        shell: bash
        run: |
          shopt -s globstar nullglob
          changed=false
          for img in public/images/**/*.{png,PNG,jpg,JPG,jpeg,JPEG}; do
            [ -e "$img" ] || continue
            out="${img%.*}.webp"
            if [ ! -f "$out" ] || [ "$img" -nt "$out" ]; then
              cwebp -q 80 "$img" -o "$out"
              echo "Converted: $img -> $out"
              changed=true
            fi
          done
          echo "changed=$changed" >> $GITHUB_OUTPUT
        id: convert

      - name: Commit optimized images
        if: steps.convert.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/images/**/*.webp || true
          git commit -m "chore(images): optimize to webp"
          git push
